### ISSUE TITLE
Application Process Request Status not working as expected

### ISSUE THREAD

**Issue by alicialhall** [xebialabs-community/xlr-ucd-plugin#3]
Hi there, I have a query that is running 30 seconds in UCD, which I'm calling from a template in XLR. I tried setting the polling interval to 10 seconds, polling 10 times, and it received a status back to XLR only after (10*10) = 100 seconds, not when the job finished in UCD. I then tried (10*20) and (10* 25), with the same result. I only received back a status of "Closed" with a Request Status of "Succeeded", after 200 and 250 seconds, respectively. I then tried 10 seconds with the polling interval at 0 (infinite), and after 7 minutes of waiting for a response back (query ran 30 seconds in UCD), I aborted. How is this request status polling supposed to work -- should it not respond back with a status when the query is done?

**Comment by jdewinne** [comment]
Based on the [code](https://github.com/xebialabs-community/xlr-ucd-plugin/blob/master/src/main/resources/ucd/UCDClient.py#L81) the RequestStatus needs to be in a `CLOSED` or `FAULTED` state in order to break out of the polling. Could it be that the Application Process Request never reaches that state?

**Comment by alicialhall** [comment]
Thanks, Joris.  Is the status field that it's looking for the finalStatus property in UCD?  I see on the job that we were running that it's set to "Success", so want to make sure that I tell our automation engineers to change the right field.

**Comment by jdewinne** [comment]
The implementation at this moment is based on the following [documentation](https://www.ibm.com/support/knowledgecenter/SS4GSP_6.2.3/com.ibm.udeploy.api.doc/topics/rest_cli_applicationprocessrequest_requeststatus_get.html). And the fields we're looking for are `requestStatus` and `requestResult`.

**Comment by alicialhall** [comment]
Thanks for that detail, Joris... the team can't figure out whether the API is correctly returning those values.  Is it possible to have a conversation to figure this out?

**Comment by alicialhall** [comment]
Joris, I checked the statuses being returned via the API, and it's Closed in requestStatus and Succeeded in requestResult, but XLR is not getting the status back to it.

**Comment by jdewinne** [comment]
Is it `Closed` or `CLOSED` that is being returned? Same question for `Succeeded` vs  `SUCCEEDED`?

**Comment by alicialhall** [comment]
it's returning CLOSED and SUCCEEDED.

**Comment by jdewinne** [comment]
ok. I'll send you a meeting invite for a call this week. Let me know if that works.
