### ISSUE TITLE
D.AI Release v24.1.2 and UCD v8.0.0.1 integration issues

### ISSUE THREAD

**Issue by ThirumalRanganathan** [xebialabs-community/xlr-ucd-plugin#7]
Hi,
We are running Digital.AI Release v24.1.2, UDeploy v8.0.0.1 and using UDeploy plugin v2.0.5 in Digital.AI Release. When we tried to trigger an UDeploy deployment from the plugin task, we see the attached error. 

![UCD_Error_From_DAIR-github](https://github.com/xebialabs-community/xlr-ucd-plugin/assets/58518258/4624ac35-7891-446a-9c59-d43879dc1c61)

UDeploy Task Type:
Ucd: Application Process Request

Error:
Exception during execution:
javax.script.ScriptException: java.lang.ClassCastException: java.lang.ClassCastException: class com.xebialabs.xlrelease.domain.configuration.HttpConnection$AuthenticationMethod cannot be cast to class java.lang.String (com.xebialabs.xlrelease.domain.configuration.HttpConnection$AuthenticationMethod is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap') in <script> at line number 14

**Comment by droberts2013** [comment]
Resolved.  See commit f288bd7b966e801a01b0f7226af819887b00129c, tag v2.0.6, version 2.0.6.
